### ISSUE TITLE
Separate the Speakers page into 50 individual pages

### ISSUE THREAD

**Issue by jakemaines** [RevolutionVA/website2017#24]
Each sub page under the speakers section should be optimized for a keyword phrase based on the topic that the speaker will be presenting on.

**Comment by jakemaines** [comment]
Make sure each of these pages has a button that directs to the ticketing page: https://ti.to/revolutionva/revolutionconf-2017

**Comment by jakemaines** [comment]
When adding pages make the Meta Name, Meta Description, and Alt Tag the same as the page title.

**Comment by iambriansreed** [comment]
I'll knock this out.

**Comment by iambriansreed** [comment]
Moved to TODO.
